#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export DROPBOX="$HOME/Dropbox"
export WIKI="$HOME/vimwiki_html"
export WIKI_SOURCE="$HOME/vimwiki"
export CODE_HOME="$HOME/code"
export PROJECTS="$CODE_HOME"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export PAGER="less -X"
export MANPAGER="$PAGER"
export TERM=xterm-256color

# editor
alias vim=nvim
export EDITOR=nvim
export VISUAL=nvim

## java homes
export GROOVY_HOME="/usr/local/opt/groovy/libexec"
export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
export JAVA_8_GRAALVM_HOME="/Library/Java/JavaVirtualMachines/graalvm-ce-19.0.0/Contents/Home"
export JAVA_13_HOME=$(/usr/libexec/java_home -v13)
export JAVA_17_HOME=$(/usr/libexec/java_home -v17)

alias -g java8='export JAVA_HOME=$JAVA_8_HOME'
alias -g java13='export JAVA_HOME=$JAVA_13_HOME'
alias -g java17='export JAVA_HOME=$JAVA_17_HOME'
alias -g javaGraal='export JAVA_HOME=$JAVA_8_GRAALVM_HOME'

function javaSelect() {
    local version verbose

    version=$1
    verbose=${2:-true}

    case $version in
        8)
            java8
            # export PATH="$JAVA_HOME/bin:$PATH"
            $verbose && echo "Selected Java 8"
            $verbose && echo "$JAVA_HOME"
            ;;
        11)
            java11
            # export PATH="$JAVA_HOME/bin:$PATH"
            $verbose && echo "Selected Java 11"
            $verbose && echo "$JAVA_HOME"
            ;;
        13)
            java13
            # export PATH="$JAVA_HOME/bin:$PATH"
            $verbose && echo "Selected Java 13"
            $verbose && echo "$JAVA_HOME"
            ;;
        17)
            java17
            # export PATH="$JAVA_HOME/bin:$PATH"
            $verbose && echo "Selected Java 17"
            $verbose && echo "$JAVA_HOME"
            ;;
        graal)
            javaGraal
            # export PATH="$JAVA_HOME/bin:$PATH"
            $verbose && echo "Selected Java GraalVM"
            $verbose && echo "$JAVA_HOME"
            ;;
        *)
            $verbose && echo "Unknown java: $version"
            $verbose && echo "$JAVA_HOME"
            ;;
    esac
}

## default to Java 16
javaSelect 16 false

# use more up-to-date SSL in shell commands
export PATH="/usr/local/opt/openssl/bin:$PATH"

# brew installed things
export PATH="/usr/local/bin:$PATH"

# java
export JABBA_HOME="$HOME/.jabba"
[ -s "$JABBA_HOME/jabba.sh" ] && source "$JABBA_HOME/jabba.sh"

# node setup
## node version manager (nvm)
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# python
export WORKON_HOME="$HOME/.virtualenvs"
export PYTHONSTARTUP="$HOME/.pystartup"
export PROJECT_HOME="$CODE_HOME"
VIRTUALENV_WRAPPER_PATH="/usr/local/bin/virtualenvwrapper_lazy.sh"
source $VIRTUALENV_WRAPPER_PATH

# rvm
export PATH="$HOME/.rvm/bin:$PATH"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# go
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# nix
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then . "$HOME/.nix-profile/etc/profile.d/nix.sh"; fi # added by Nix installer

# emacs
export PATH="$HOME/.emacs.d/bin:$PATH"

# my crap
source "$HOME/.config/feltnerm/aliases.sh"
source "$HOME/.config/feltnerm/functions.sh"

export PATH="$HOME/.config/feltnerm/bin:$PATH"
