# Automatically migrated from legacy .beetsconfig.

color: true
threaded: true
plugins: lastgenre scrub inline fetchart ftintitle importfeeds mpdupdate
directory: /stash/library/music
library: /var/lib/beets/library.blb

import:
    copy: true
    move: false
    write: true
    log: /stash/_meta/music/beetslog.txt
    resume: true
    art: true
    quiet_fallback: skip
art_filename: cover
ignore: .AppleDouble ._* *~ .DS_Store

paths:
    default: $albumartist/$year - $album [$format]/$track - $title
    singleton: $artist/$year - $album [$format]/$title
    comp: __COMPILATIONS/$year - $album [$format]/$track - $title - $artist
    albumtype:soundtrack: '%if{$composer,$composer,__SOUNDTRACKS}/$year - $album [$format]/$track - $title'

fetchart:
    auto: true

scrub:
    auto: true

mpdupdate:
    host: localhost
    port: 6600

importfeeds:
    format: m3u
    dir: /var/lib/mpd/playlists/
    m3u_name: recentlty_added.m3u
